/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mitho.khana.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public adminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        customerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        foodLabel = new javax.swing.JLabel();
        foodField = new javax.swing.JTextField();
        prepLabel = new javax.swing.JLabel();
        prepField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryField = new javax.swing.JTextField();
        ingreLabel = new javax.swing.JLabel();
        ingreField = new javax.swing.JTextField();
        dietaryLabel = new javax.swing.JLabel();
        dietaryField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        snLabel = new javax.swing.JLabel();
        snfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerButton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        customerButton.setForeground(new java.awt.Color(255, 51, 51));
        customerButton.setText("Customer Page");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(customerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome to Mitho Khana");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 360, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Mitho Khana\\src\\images\\yummy.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-70, 0, 1070, 130);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2), "Admin Page", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foodLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        foodLabel.setText("Food Name");
        jPanel3.add(foodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 40));

        foodField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        foodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodFieldActionPerformed(evt);
            }
        });
        jPanel3.add(foodField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 240, 40));

        prepLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        prepLabel.setText("Preparation Time");
        jPanel3.add(prepLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 40));

        prepField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        prepField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prepFieldActionPerformed(evt);
            }
        });
        jPanel3.add(prepField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 40));

        categoryLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        categoryLabel.setText("Category");
        jPanel3.add(categoryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 40));

        categoryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryFieldActionPerformed(evt);
            }
        });
        jPanel3.add(categoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 40));

        ingreLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        ingreLabel.setText("Main Ingredient");
        jPanel3.add(ingreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 140, 30));

        ingreField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(ingreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 40));

        dietaryLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        dietaryLabel.setText("Dietary Preference");
        jPanel3.add(dietaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 130, 30));

        dietaryField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(dietaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 40));

        addButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        addButton.setText("ADD");
        addButton.setActionCommand("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 80, 40));

        updateButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel3.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, 40));

        deleteButton.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel3.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 100, 40));

        snLabel.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        snLabel.setText("S.N");
        jPanel3.add(snLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 30));

        snfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(snfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 30));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 130, 290, 570);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.N", "Food Name", "Category", "Preparation Time", "Main Ingredients", "Dietary Preference"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 140, 710, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prepFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prepFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prepFieldActionPerformed

    private void categoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(snfield.getText().equals("")||foodField.getText().equals("")||categoryField.getText().equals("")|| prepField.getText().equals("")||ingreField.getText().equals("")||dietaryField.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Please enter all the data !!!");
        }else{
            String data[]= {snfield.getText(),foodField.getText(),categoryField.getText(), prepField.getText(),ingreField.getText(),dietaryField.getText()};
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        tblModel.addRow(data);
        JOptionPane.showMessageDialog(this,"Add data successfully !!!");
        snfield.setText("");
        foodField.setText("");
        categoryField.setText("");
        prepField.setText("");
        ingreField.setText("");
        dietaryField.setText("");
        
            
        }
       
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void foodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodFieldActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        // TODO add your handling code here:
        Dashboard db = new Dashboard();
        db.setVisible(true);
        db.pack();
        db.setLocationRelativeTo(null); 
        this.dispose();
    }//GEN-LAST:event_customerButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {
    //if single row is selected than update

    String sn = snfield.getText();
    String name = foodField.getText();
    String category = categoryField.getText();
    String prep = prepField.getText();
    String ingredients = ingreField.getText();
    String diet = dietaryField.getText();

    //set updated value on table row
    tblModel.setValueAt(sn, jTable1.getSelectedRow(), 0);
    tblModel.setValueAt(name, jTable1.getSelectedRow(), 1);
    tblModel.setValueAt(category, jTable1.getSelectedRow(), 2);
    tblModel.setValueAt(prep, jTable1.getSelectedRow(), 3);
    tblModel.setValueAt(ingredients, jTable1.getSelectedRow(), 4);
    tblModel.setValueAt(diet, jTable1.getSelectedRow(), 5);

    //update message display
    JOptionPane.showMessageDialog(this, "Update Successfully.");
    } else{
            if(jTable1.getRowCount()==0) {  //if table is empty
    JOptionPane.showMessageDialog(this, "Table is Empty..");
    }else{                          
    //if row is not selected or multiple row is selected than
    JOptionPane.showMessageDialog(this, "Please select Single Row For Update..");
    }
        }
        
        
        
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        
        //delete row
        if(jTable1.getSelectedRowCount()==1) {
        //if single row is selected than delete
        tblModel.removeRow(jTable1.getSelectedRow());
         } else {
        if(jTable1.getRowCount()==0) {
        // if table is empty (no data) than display message
        JOptionPane.showMessageDialog(this, "Table is Empty.");
         } else {
        // if table is not empty but row is not selected or multiple row is selected
    JOptionPane.showMessageDialog(this,"Please select Single Row For Deletion");
    }
}
        
            
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
   
         
         String tblsn = tblModel.getValueAt(jTable1.getSelectedRow(), 0).toString();
         String tblname = tblModel.getValueAt(jTable1.getSelectedRow(), 1).toString();
         String tblcategory = tblModel.getValueAt(jTable1.getSelectedRow(), 2).toString();
         String tblprep = tblModel.getValueAt(jTable1.getSelectedRow(), 3).toString();
         String tblingredient = tblModel.getValueAt(jTable1.getSelectedRow(), 4).toString();
         String tbldiet = tblModel.getValueAt(jTable1.getSelectedRow(), 5).toString();
         
         
        snfield.setText("tblsn");
        foodField.setText("tblname");
        categoryField.setText("tblcategory");
        prepField.setText("tblprep");
        ingreField.setText("tblingredient");
        dietaryField.setText("tbldiet");
         
         
         
         
         
         
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField categoryField;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton customerButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField dietaryField;
    private javax.swing.JLabel dietaryLabel;
    private javax.swing.JTextField foodField;
    private javax.swing.JLabel foodLabel;
    private javax.swing.JTextField ingreField;
    private javax.swing.JLabel ingreLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField prepField;
    private javax.swing.JLabel prepLabel;
    private javax.swing.JLabel snLabel;
    private javax.swing.JTextField snfield;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
